# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpJItPhMjBzA4z2MynI9aOmKX3qe3BTI
"""

import pandas as pd
import matplotlib.pyplot as plt

FONTSIZE_TITLE = 20
FONTSIZE_LABEL = 18
FONTSIZE_TICK = 18
FONTSIZE_LEGEND = 18

participant_df = pd.read_csv('participant_gini_PR.csv')

plt.figure(figsize=(12, 6))
plt.plot(participant_df['year'], participant_df['participant_gini'],
         marker='^', linewidth=2, markersize=8, color='#F18F01', label='Participant Gini')
plt.xlabel('Year', fontsize=FONTSIZE_LABEL)
plt.ylabel('Gini Coefficient', fontsize=FONTSIZE_LABEL)
plt.title('Gini Coefficient of Participant Activity Distribution Over Time',
          fontsize=FONTSIZE_TITLE, fontweight='bold')
plt.legend(fontsize=FONTSIZE_LEGEND)
plt.grid(True, alpha=0.3)
plt.xticks(participant_df['year'], rotation=45, fontsize=FONTSIZE_TICK)
plt.yticks(fontsize=FONTSIZE_TICK)
plt.ylim(0, 1)
plt.tight_layout()
plt.savefig('participant_gini_plot.png', dpi=300, bbox_inches='tight')
print("Figure saved to: participant_gini_plot.png")
plt.show()





