# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpJItPhMjBzA4z2MynI9aOmKX3qe3BTI
"""

import pandas as pd
import matplotlib.pyplot as plt

FONT_SIZES = {
    'main_title': 20,          # Main title
    'axis_label': 18,          # Axis labels
    'legend': 16,              # Legend
    'tick_label': 16,          # Tick labels
    'annotation': 16,          # Annotation text
}

plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial']
plt.rcParams['axes.unicode_minus'] = False

csv_path = 'PullRequest_overtime.csv'
yearly_stats = pd.read_csv(csv_path)

fig, ax1 = plt.subplots(figsize=(16, 8))

# Left Y-axis: Total PRs (blue line)
color_total = '#2E86AB'
ax1.set_xlabel('Year', fontsize=FONT_SIZES['axis_label'], fontweight='bold')
ax1.set_ylabel('Number of Total PRs', fontsize=FONT_SIZES['axis_label'],
               fontweight='bold', color=color_total)
ax1.plot(yearly_stats['year'], yearly_stats['total_prs'],
         marker='o', linewidth=3, markersize=10, label='Total PRs',
         color=color_total, alpha=0.9)
ax1.tick_params(axis='y', labelcolor=color_total, labelsize=FONT_SIZES['tick_label'])
ax1.tick_params(axis='x', labelsize=FONT_SIZES['tick_label'])
ax1.grid(True, alpha=0.3, linestyle='--', linewidth=0.5)

# Right Y-axis: Merge Percentage (red line)
ax2 = ax1.twinx()
color_percentage = '#D62828'
ax2.set_ylabel('Merge Percentage (%)', fontsize=FONT_SIZES['axis_label'],
               fontweight='bold', color=color_percentage)
ax2.plot(yearly_stats['year'], yearly_stats['merge_percentage'],
         marker='s', linewidth=3, markersize=10, label='Merge Percentage',
         color=color_percentage, alpha=0.9)
ax2.tick_params(axis='y', labelcolor=color_percentage, labelsize=FONT_SIZES['tick_label'])
ax2.set_ylim(0, 100)

ax1.set_title('PR Count and Merge Rate Over Time',
              fontsize=FONT_SIZES['main_title'], pad=20, fontweight='bold')

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2,
           loc='upper left', fontsize=FONT_SIZES['legend'], framealpha=0.9)

total_prs_sum = yearly_stats['total_prs'].sum()
overall_merge_rate = yearly_stats['merge_percentage'].mean()

ax1.text(0.02, 0.98,
         f'Total: {total_prs_sum} PRs\nAvg Merge Rate: {overall_merge_rate:.1f}%',
         transform=ax1.transAxes, fontsize=FONT_SIZES['annotation'],
         verticalalignment='top',
         bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.7))

plt.tight_layout()

plot_output_path = 'pr_count_and_merge_rate.png'
plt.savefig(plot_output_path, dpi=300, bbox_inches='tight')
print(f"Figure saved as: {plot_output_path}")
plt.show()

