# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wz7ZfFLhEiTEWLj7VXPJrRrcZp6SiJpB
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

file_path = 'BIP_Content.xlsx'
df = pd.read_excel(file_path)

print(f"Dataset shape: {df.shape}")
print("\nFirst 5 rows:")
print(df.head())

print("\nColumn names:")
print(df.columns.tolist())

import pandas as pd
import re

def parse_bip_header(content):
    """Parse BIP header information from content (extract specified fields only)"""
    # Handle escaped newline characters
    if isinstance(content, str):
        content = content.replace('\\n', '\n')
    else:
        content = str(content)

    result = {
        'BIP': None,
        'Title': None,
        'Author': None,
        'Comments-Summary': None,
        'Comments-URI': None,
        'Status': None,
        'Type': None,
        'Created': None,
        'Superseded-By': None
    }

    # For most fields, use single-line matching
    single_line_fields = ['BIP', 'Title', 'Comments-Summary', 'Comments-URI',
                          'Status', 'Type', 'Created', 'Superseded-By']

    for key in single_line_fields:
        pattern = rf'^\s*{re.escape(key)}:\s*(.+?)$'
        match = re.search(pattern, content, re.MULTILINE | re.IGNORECASE)
        if match:
            value = match.group(1).strip()
            # Special handling for Status field: remove parentheses and content after
            if key == 'Status' and '(' in value:
                value = value.split('(')[0].strip()
            result[key] = value

    # Special handling for Author field: support multiple lines
    # Match lines starting with "Author:", then all subsequent indented lines until next field
    author_pattern = r'Author:\s*(.+?)(?=\n\s*[A-Z][a-z\-]+:|$)'
    author_match = re.search(author_pattern, content, re.DOTALL | re.IGNORECASE)

    if author_match:
        author_text = author_match.group(1).strip()
        author_text = re.sub(r'\s+', ' ', author_text)
        result['Author'] = author_text

    return result

parsed_data = df['content'].apply(parse_bip_header)

df_proposal = pd.DataFrame(parsed_data.tolist())

print("First 5 rows of parsed dataset:")
print(df_proposal.head())
print("\nDataset shape:")
print(df_proposal.shape)
print("\nColumn names:")
print(df_proposal.columns.tolist())

# Temporal analysis of proposals count

def parse_date(date_str):
    if pd.isna(date_str):
        return None
    date_str = str(date_str).strip()
    formats = ['%Y-%m-%d', '%d-%m-%Y', '%m-%d-%Y']
    for fmt in formats:
        try:
            from datetime import datetime
            return datetime.strptime(date_str, fmt)
        except:
            continue
    return None

df_proposal['created_date'] = df_proposal['Created'].apply(parse_date)
df_proposal['year'] = df_proposal['created_date'].dt.year

year_dist = df_proposal['year'].value_counts().sort_index()
print("\nDistribution by year:")
print(year_dist)

# Temporal Analysis by BIP Status

year_total = df_proposal['year'].value_counts().sort_index()
status_by_year = df_proposal.groupby(['year', 'Status']).size().unstack(fill_value=0)

title_fontsize = 24
axis_label_fontsize = 20
tick_fontsize = 20
legend_fontsize = 20

plt.figure(figsize=(14, 8))

# 1. All BIPs (total)
plt.plot(year_total.index,
         year_total.values,
         marker='o',
         linewidth=4,
         markersize=10,
         label='All BIPs',
         color='#2E86AB',
         linestyle='-')

# 2. Final (red)
if 'Final' in status_by_year.columns:
    plt.plot(status_by_year.index,
             status_by_year['Final'],
             marker='^',
             linewidth=4,
             markersize=8,
             label='Final',
             color='#E63946',
             linestyle='--')

plt.title('BIP Proposals Over Time: All and Final (2011-2025)',
          fontsize=title_fontsize, fontweight='bold', pad=20)
plt.xlabel('Year', fontsize=axis_label_fontsize, fontweight='bold')
plt.ylabel('Number of Proposals', fontsize=axis_label_fontsize, fontweight='bold')

plt.xticks(year_total.index, rotation=45, ha='right', fontsize=tick_fontsize)
plt.yticks(fontsize=tick_fontsize)

plt.grid(True, alpha=0.3, linestyle='--')

plt.legend(fontsize=legend_fontsize, loc='best', framealpha=0.9)

plt.tight_layout()

plt.savefig('bip_temporal_trend_selected.png',
            dpi=500, bbox_inches='tight')
plt.show()

# ===== Statistical Summary =====
print(f"\nStatistical Summary:")
print(f"  Total number of all BIPs: {year_total.sum()}")
if 'Final' in status_by_year.columns:
    print(f"  Total number of Final: {status_by_year['Final'].sum()}")