# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpJItPhMjBzA4z2MynI9aOmKX3qe3BTI
"""

import pandas as pd
import matplotlib.pyplot as plt

FONTSIZE_TITLE = 20
FONTSIZE_LABEL = 18
FONTSIZE_TICK = 18
FONTSIZE_LEGEND = 18
FONTSIZE_ANNOTATION = 16

csv_path = 'Yearly_reviews_comments.csv'
yearly_stats = pd.read_csv(csv_path)

fig, ax = plt.subplots(figsize=(14, 7))

ax.plot(yearly_stats['year'], yearly_stats['total_reviews'],
        marker='o', linewidth=2.5, markersize=9, label='Total Reviews',
        color='#A23B72', alpha=0.9)

ax.plot(yearly_stats['year'], yearly_stats['total_comments'],
        marker='s', linewidth=2.5, markersize=9, label='Total Comments',
        color='#2E86AB', alpha=0.9)

ax.set_xlabel('Year', fontsize=FONTSIZE_LABEL, fontweight='bold')
ax.set_ylabel('Count', fontsize=FONTSIZE_LABEL, fontweight='bold')
ax.set_title('Total Reviews and Comments Over Time',
             fontsize=FONTSIZE_TITLE, pad=15, fontweight='bold')

ax.legend(fontsize=FONTSIZE_LEGEND, loc='best', framealpha=0.9)

ax.grid(True, alpha=0.3, linestyle='--', linewidth=0.5)

ax.tick_params(axis='x', rotation=45, labelsize=FONTSIZE_TICK)
ax.tick_params(axis='y', labelsize=FONTSIZE_TICK)

total_reviews_sum = yearly_stats['total_reviews'].sum()
total_comments_sum = yearly_stats['total_comments'].sum()

ax.text(0.02, 0.98,
        f'Total Reviews: {int(total_reviews_sum):,}\nTotal Comments: {int(total_comments_sum):,}',
        transform=ax.transAxes, fontsize=FONTSIZE_ANNOTATION,
        verticalalignment='top',
        bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.7))

plt.tight_layout()

plot_output_path = 'reviews_comments_over_time.png'
plt.savefig(plot_output_path, dpi=300, bbox_inches='tight')
print(f"Figure saved to: {plot_output_path}")
plt.show()

